# Dart/Flutter lint configuration
include: package:flutter_lints/flutter.yaml

#analyzer:
#  exclude:
#    - build/**
#    - "**/*.g.dart"
#    - "**/*.freezed.dart"
#    - "**/*.gen.dart"
#    - "**/*.gr.dart"
#    - "lib/generated_plugin_registrant.dart"

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: true
    directives_ordering: true
    prefer_final_locals: true
#    always_use_package_imports
#    prefer_const_literals_to_create_immutables
#    sort_constructors_first
#    use_super_parameters
#    omit_local_variable_types
#    unawaited_futures
#    unnecessary_late
#    cancel_subscriptions
#    close_sinks
